App:
  Addr: ":8080"
  RequestTimeout: 60s            # 原 5s -> 60s，确保语音拨号+播报不被过早取消
  IdempotencyTTL: 5m
  SyncPriorityThreshold: 4  # 优先级 >= 4 的消息同步处理，< 4 的异步处理

Storage:
  RedisAddr: "127.0.0.1:6380"
  Namespace: "push-dev2"
  MaxKeep: 10000000
  TTL: 8760h
  InboxMaxPerUser: 1000
  InboxTTL: 720h
  # MySQL配置
  MySQL:
    DSN: "root:password@tcp(127.0.0.1:3306)/push_service?charset=utf8mb4&parseTime=True&loc=Local"
    MaxOpenConns: 100
    MaxIdleConns: 10
    ConnMaxLifetime: 3600s
  # 异步落库配置
  AsyncSync:
    Enabled: true
    BatchSize: 100
    FlushInterval: 10s
    RetryAttempts: 3
    WorkerCount: 5

NSQ:
  Topic: "push-messages"
  Channel: "push-workers"
  NsqdTCPAddrs: ["127.0.0.1:4150"]
  LookupdHTTPAddrs: []
  MaxInFlight: 128
  Concurrency: 8
  ProducerAddr: "127.0.0.1:4150"
  ConsumerEnabled: true
  DLQTopic: "push-messages.DLQ"
  MaxConsumeAttemptsBeforeDLQ: 5
  # 优先级队列配置
  PriorityTopics:
    high: "push-messages-high"     # 高优先级队列
    medium: "push-messages-medium" # 中优先级队列
    low: "push-messages-low"       # 低优先级队列
  PriorityThresholds:
    high: 4    # 优先级 >= 4 的消息使用高优先级队列
    medium: 2  # 优先级 >= 2 的消息使用中优先级队列
    low: 1     # 优先级 >= 1 的消息使用低优先级队列

# 语音和短信专用队列配置
VoiceQueue:
  Topic: "voice-messages"         # 语音消息专用主题
  Channel: "voice-workers"        # 语音消息消费通道
  NsqdTCPAddrs: ["127.0.0.1:4150"]
  LookupdHTTPAddrs: []
  MaxInFlight: 32                 # 语音消息最大并行处理数
  Concurrency: 2                  # 语音消息并发消费者数
  ProducerAddr: "127.0.0.1:4150"
  ConsumerEnabled: true
  DLQTopic: "voice-messages.DLQ"  # 语音消息死信队列
  MaxConsumeAttemptsBeforeDLQ: 3  # 语音消息最大重试次数

SMSQueue:
  Topic: "sms-messages"           # 短信消息专用主题
  Channel: "sms-workers"          # 短信消息消费通道
  NsqdTCPAddrs: ["127.0.0.1:4150"]
  LookupdHTTPAddrs: []
  MaxInFlight: 64                 # 短信消息最大并行处理数
  Concurrency: 4                  # 短信消息并发消费者数
  ProducerAddr: "127.0.0.1:4150"
  ConsumerEnabled: true
  DLQTopic: "sms-messages.DLQ"    # 短信消息死信队列
  MaxConsumeAttemptsBeforeDLQ: 3  # 短信消息最大重试次数

Providers:
  Web: {}
  Email:
    From: "1395449375@qq.com"
    FromName: "Push Service Notification"
    SMTPHost: "smtp.qq.com"
    SMTPPort: 587
    Username: "1395449375@qq.com"
    Password: "wpffzatkfgwuhcgc"
    UseTLS: true
    UseSSL: false
    Timeout: 10s
    Retry: {MaxAttempts: 3, Backoff: 500ms}
  SMS:
    Sign: "ACME"
    Timeout: 12s                 # 原 10s -> 12s 略放宽
    Retry: {MaxAttempts: 2, Backoff: 500ms}  # 原 1 次 -> 2 次
  Voice:
    Timeout: 60s                 # 原 45s -> 60s 与全局一致，避免父 ctx 更短
    Retry: {MaxAttempts: 3, Backoff: 2s}     # 原 1 次 -> 3 次，提高瞬时失败容错
  Modem:
    Enabled: true
    PortName: "COM4"
    BaudRate: 19200
    ReadTimeout: 5s
    CommandTimeout: 15s          # 原 10s -> 15s，复杂指令更稳
    DialTimeout: 30s             # 拨号等待保持
    CallDuration: 30s            # 原 15s -> 30s，允许更长播报
    SMSEncoding: "UTF-8"
    VoiceQueueSize: 10
    SMSQueueSize: 20
    MaxConcurrentVoice: 1
    MaxConcurrentSMS: 1
    Timeout: 60s                 # 原 30s -> 60s，与语音一致
    Retry: {MaxAttempts: 3, Backoff: 2s}     # 原 2 -> 3

MessageFormats:
  # 通用消息字段，所有消息类型都会包含这些字段
  # 系统会自动将 CommonFields 中的字段添加到每个消息类型中
  CommonFields:
    - name: "priority"
      type: "int"
      required: false
      description: "消息优先级（1-5，5为最高）"
    - name: "sender"
      type: "uint64"
      required: true
      description: "发送人的用户ID"

  # 以下各消息类型会自动包含 CommonFields 中定义的所有字段

  Msg:
    type: "push.Msg"
    fields:
      - name: "appId"
        type: "string"
        required: true
        description: "应用Id, 由应用方配置, 应当为常量, 服务不做校验"
      - name: "content"
        type: "object"
        required: true
        description: "通知内容，预览时显示"
      - name: "type"
        type: "string"
        required: true
        description: "通知类型，可设置为 等级(Info/Warn/Error) or 业务类型"
  Notification:
    type: "push.Notification"
    fields:
      - name: "title"
        type: "string"
        required: true
        description: "通知标题"
      - name: "body"
        type: "string"
        required: true
        description: "通知内容"
  Alert:
    type: "push.Alert"
    fields:
      - name: "severity"
        type: "string"
        required: true
        description: "告警严重程度 (critical/high/medium/low)"
      - name: "source"
        type: "string"
        required: true
        description: "告警来源系统"
      - name: "description"
        type: "string"
        required: true
        description: "告警详细描述"
      - name: "timestamp"
        type: "string"
        required: false
        description: "告警发生时间"

  # 专门的语音消息格式 - 只需要内容
  VoiceMessage:
    type: "push.VoiceMessage"
    channels: ["voice"]
    fields:
      - name: "content"
        type: "string"
        required: true
        description: "语音播报内容，支持中文文本转语音"

  # 专门的短信消息格式 - 只需要内容  
  SMSMessage:
    type: "push.SMSMessage"
    channels: ["sms"]
    fields:
      - name: "content"
        type: "string"
        required: true
        description: "短信文本内容，建议控制在70字以内"
  DeviceOnline:
    type: "push.DeviceOnline"
    fields:
      - name: "deviceId"
        type: "string"
        required: true
        description: "设备唯一标识"
      - name: "deviceName"
        type: "string"
        required: false
        description: "设备名称"
      - name: "onlineTime"
        type: "string"
        required: true
        description: "上线时间"
      - name: "location"
        type: "string"
        required: false
        description: "设备位置"
  # 邮件发送消息类型
  Email:
    type: "push.Email"
    channels: ["email"]
    fields:
      - name: "recipientIds"
        type: "[]string"
        required: true
        description: "收件人ID列表"
      - name: "subject"
        type: "string"
        required: true
        description: "邮件主题"
      - name: "content"
        type: "string"
        required: true
        description: "邮件内容（支持HTML）"
      - name: "isHtml"
        type: "bool"
        required: false
        description: "是否HTML格式邮件"
      - name: "cc"
        type: "[]string"
        required: false
        description: "抄送人ID列表"


